chmod 755 ./src/compile_all.sh
chmod 755 ./src/CombineSynthPopul/*.sh
chmod 755 ./src/GetAdminUnits/*.sh
chmod 755 ./src/JobCreator/*.sh
chmod 755 ./src/MashAdminUnits/*.sh
chmod 755 ./src/PatchFileMaker/*.sh
chmod 755 ./src/Sim/*.sh
chmod 755 ./src/SynthPopul/*.sh
chmod 755 ./bin-linux/CombineSynthPopul/combine
chmod 755 ./bin-linux/GetAdminUnits/get_admin_units.sh
chmod 755 ./bin-linux/MashAdminUnits/mashadmin
chmod 755 ./bin-linux/PatchFileMaker/makePatches.sh
chmod 755 ./bin-linux/Sim/sim
chmod 755 ./bin-linux/SynthPopul/SynthPopul
chmod 755 ./bin-linux/SynthPopul/*.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Algeria/run__SynthPopul__Algeria.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Angola/run__SynthPopul__Angola.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Benin/run__SynthPopul__Benin.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Botswana/run__SynthPopul__Botswana.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Burkina_Faso/run__SynthPopul__Burkina_Faso.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Burundi/run__SynthPopul__Burundi.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Cameroon/run__SynthPopul__Cameroon.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Cape_Verde/run__SynthPopul__Cape_Verde.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Centr_African_Rep/run__SynthPopul__Centr_African_Rep.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Chad/run__SynthPopul__Chad.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Comoros/run__SynthPopul__Comoros.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Congo_Brazzaville/run__SynthPopul__Congo_Brazzaville.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Congo_Dem_Rep/run__SynthPopul__Congo_Dem_Rep.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Cote_dIvore/run__SynthPopul__Cote_dIvore.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Djibouti/run__SynthPopul__Djibouti.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Egypt/run__SynthPopul__Egypt.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Equatorial_Guinea/run__SynthPopul__Equatorial_Guinea.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Eritrea/run__SynthPopul__Eritrea.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Ethiopia/run__SynthPopul__Ethiopia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Gabon/run__SynthPopul__Gabon.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Gambia/run__SynthPopul__Gambia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Ghana/run__SynthPopul__Ghana.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Guinea/run__SynthPopul__Guinea.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Guinea-Bissau/run__SynthPopul__Guinea-Bissau.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Kenya/run__SynthPopul__Kenya.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Lesotho/run__SynthPopul__Lesotho.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Liberia/run__SynthPopul__Liberia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Libya/run__SynthPopul__Libya.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Madagascar/run__SynthPopul__Madagascar.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Malawi/run__SynthPopul__Malawi.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Mali/run__SynthPopul__Mali.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Mauritania/run__SynthPopul__Mauritania.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Mauritius/run__SynthPopul__Mauritius.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Morocco/run__SynthPopul__Morocco.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Mozambique/run__SynthPopul__Mozambique.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Namibia/run__SynthPopul__Namibia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Niger/run__SynthPopul__Niger.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Nigeria/run__SynthPopul__Nigeria.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Reunion/run__SynthPopul__Reunion.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Rwanda/run__SynthPopul__Rwanda.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Sao_Tome_Principe/run__SynthPopul__Sao_Tome_Principe.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Senegal/run__SynthPopul__Senegal.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Seychelles/run__SynthPopul__Seychelles.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Sierra_Leone/run__SynthPopul__Sierra_Leone.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Somalia/run__SynthPopul__Somalia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/South_Africa/run__SynthPopul__South_Africa.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Sudan/run__SynthPopul__Sudan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Swaziland/run__SynthPopul__Swaziland.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Tanzania/run__SynthPopul__Tanzania.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Togo/run__SynthPopul__Togo.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Tunisia/run__SynthPopul__Tunisia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Uganda/run__SynthPopul__Uganda.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Zambia/run__SynthPopul__Zambia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Africa/Zimbabwe/run__SynthPopul__Zimbabwe.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Afghanistan/run__SynthPopul__Afghanistan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Bahrain/run__SynthPopul__Bahrain.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Bangladesh/run__SynthPopul__Bangladesh.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Bhutan/run__SynthPopul__Bhutan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Burma/run__SynthPopul__Burma.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Cambodia/run__SynthPopul__Cambodia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/China/run__SynthPopul__China.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Hong_Kong/run__SynthPopul__Hong_Kong.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/India/run__SynthPopul__India.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Indonesia/run__SynthPopul__Indonesia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Iran/run__SynthPopul__Iran.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Iraq/run__SynthPopul__Iraq.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Israel/run__SynthPopul__Israel.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Japan/run__SynthPopul__Japan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Jordan/run__SynthPopul__Jordan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Kazakhstan/run__SynthPopul__Kazakhstan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Kuwait/run__SynthPopul__Kuwait.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Kyrgyzstan/run__SynthPopul__Kyrgyzstan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Laos/run__SynthPopul__Laos.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Lebanon/run__SynthPopul__Lebanon.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Macao/run__SynthPopul__Macao.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Malaysia/run__SynthPopul__Malaysia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Maldives/run__SynthPopul__Maldives.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Mongolia/run__SynthPopul__Mongolia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Nepal/run__SynthPopul__Nepal.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/New_Guinea/run__SynthPopul__New_Guinea.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/NKorea/run__SynthPopul__NKorea.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Oman/run__SynthPopul__Oman.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Pakistan/run__SynthPopul__Pakistan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Palest_Territory/run__SynthPopul__Palest_Territory.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Philippines/run__SynthPopul__Philippines.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Saudi_Arabia/run__SynthPopul__Saudi_Arabia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Singapore/run__SynthPopul__Singapore.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/SKorea/run__SynthPopul__SKorea.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Sri_Lanka/run__SynthPopul__Sri_Lanka.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Syria/run__SynthPopul__Syria.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Taiwan/run__SynthPopul__Taiwan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Tajikistan/run__SynthPopul__Tajikistan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Thailand/run__SynthPopul__Thailand.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Timor_Leste/run__SynthPopul__Timor_Leste.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Turkmenistan/run__SynthPopul__Turkmenistan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/United_Arab_Emirates/run__SynthPopul__United_Arab_Emirates.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Uzbekistan/run__SynthPopul__Uzbekistan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Vietnam/run__SynthPopul__Vietnam.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Asia/Yemen/run__SynthPopul__Yemen.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Anguilla/run__SynthPopul__Anguilla.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Antigua_Barbuda/run__SynthPopul__Antigua_Barbuda.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Belize/run__SynthPopul__Belize.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Bermuda/run__SynthPopul__Bermuda.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Cayman_Islands/run__SynthPopul__Cayman_Islands.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Costa_Rica/run__SynthPopul__Costa_Rica.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Cuba/run__SynthPopul__Cuba.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Dominica/run__SynthPopul__Dominica.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Dominican_Republic/run__SynthPopul__Dominican_Republic.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/El_Salvador/run__SynthPopul__El_Salvador.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Guatemala/run__SynthPopul__Guatemala.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Haiti/run__SynthPopul__Haiti.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Honduras/run__SynthPopul__Honduras.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Jamaica/run__SynthPopul__Jamaica.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Martinique/run__SynthPopul__Martinique.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Montserrat/run__SynthPopul__Montserrat.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Netherlands_Antilles/run__SynthPopul__Netherlands_Antilles.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Nicaragua/run__SynthPopul__Nicaragua.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Panama/run__SynthPopul__Panama.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Puerto_Rico/run__SynthPopul__Puerto_Rico.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/St_Kitts__Nevis/run__SynthPopul__St_Kitts__Nevis.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/The_Bahamas/run__SynthPopul__The_Bahamas.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Turks_Caicos_Islands/run__SynthPopul__Turks_Caicos_Islands.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Virgin_Islands_UK/run__SynthPopul__Virgin_Islands_UK.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Central_America/Virgin_Islands_US/run__SynthPopul__Virgin_Islands_US.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Albania/run__SynthPopul__Albania.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Andorra/run__SynthPopul__Andorra.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Armenia/run__SynthPopul__Armenia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Austria/run__SynthPopul__Austria.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Azerbaijan/run__SynthPopul__Azerbaijan.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Belarus/run__SynthPopul__Belarus.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Belgium/run__SynthPopul__Belgium.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Bosnia_Gerzegovina/run__SynthPopul__Bosnia_Gerzegovina.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Bulgaria/run__SynthPopul__Bulgaria.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Croatia/run__SynthPopul__Croatia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Cyprus/run__SynthPopul__Cyprus.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Czech_Republic/run__SynthPopul__Czech_Republic.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Denmark/run__SynthPopul__Denmark.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Estonia/run__SynthPopul__Estonia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Faroe_Islands/run__SynthPopul__Faroe_Islands.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Finland/run__SynthPopul__Finland.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/France/run__SynthPopul__France.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Georgia/run__SynthPopul__Georgia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Germany/run__SynthPopul__Germany.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Gibraltar/run__SynthPopul__Gibraltar.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Greece/run__SynthPopul__Greece.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Greenland/run__SynthPopul__Greenland.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Guernsey/run__SynthPopul__Guernsey.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Hungary/run__SynthPopul__Hungary.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Iceland/run__SynthPopul__Iceland.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Ireland/run__SynthPopul__Ireland.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Isle_of_Man/run__SynthPopul__Isle_of_Man.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Italy/run__SynthPopul__Italy.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Jersey/run__SynthPopul__Jersey.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Latvia/run__SynthPopul__Latvia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Liechtenstein/run__SynthPopul__Liechtenstein.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Lithuania/run__SynthPopul__Lithuania.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Luxembourg/run__SynthPopul__Luxembourg.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Macedonia/run__SynthPopul__Macedonia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Malta/run__SynthPopul__Malta.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Moldova/run__SynthPopul__Moldova.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Monaco/run__SynthPopul__Monaco.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Netherlands/run__SynthPopul__Netherlands.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Norway/run__SynthPopul__Norway.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Poland/run__SynthPopul__Poland.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Portugal/run__SynthPopul__Portugal.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Romania/run__SynthPopul__Romania.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Russia/run__SynthPopul__Russia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/San_Marino/run__SynthPopul__San_Marino.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Serbia/run__SynthPopul__Serbia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Slovakia/run__SynthPopul__Slovakia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Slovenia/run__SynthPopul__Slovenia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Spain/run__SynthPopul__Spain.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Sweden/run__SynthPopul__Sweden.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Switzerland/run__SynthPopul__Switzerland.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Turkey/run__SynthPopul__Turkey.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/Ukraine/run__SynthPopul__Ukraine.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Europe/United_Kingdom/run__SynthPopul__United_Kingdom.sh
chmod 755 ./bin-linux/SynthPopul/scripts/North_America/Canada/run__SynthPopul__Canada.sh
chmod 755 ./bin-linux/SynthPopul/scripts/North_America/Mexico/run__SynthPopul__Mexico.sh
chmod 755 ./bin-linux/SynthPopul/scripts/North_America/USA/run__SynthPopul__USA.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/American_Samoa/run__SynthPopul__American_Samoa.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Australia/run__SynthPopul__Australia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Fiji/run__SynthPopul__Fiji.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/French_Polynesia/run__SynthPopul__French_Polynesia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Guam/run__SynthPopul__Guam.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Kiribati/run__SynthPopul__Kiribati.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Marshall_Islands/run__SynthPopul__Marshall_Islands.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Micronesia/run__SynthPopul__Micronesia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/New_Caledonia/run__SynthPopul__New_Caledonia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/New_Zealand/run__SynthPopul__New_Zealand.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Northern_Mariana_Islands/run__SynthPopul__Northern_Mariana_Islands.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Palau/run__SynthPopul__Palau.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Samoa/run__SynthPopul__Samoa.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Solomon_Islands/run__SynthPopul__Solomon_Islands.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Tonga/run__SynthPopul__Tonga.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Tuvalu/run__SynthPopul__Tuvalu.sh
chmod 755 ./bin-linux/SynthPopul/scripts/Oceania/Vanuatu/run__SynthPopul__Vanuatu.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Argentina/run__SynthPopul__Argentina.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Aruba/run__SynthPopul__Aruba.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Barbados/run__SynthPopul__Barbados.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Bolivia/run__SynthPopul__Bolivia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Brazil/run__SynthPopul__Brazil.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Chile/run__SynthPopul__Chile.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Colombia/run__SynthPopul__Colombia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Ecuador/run__SynthPopul__Ecuador.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/French_Guiana/run__SynthPopul__French_Guiana.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Grenada/run__SynthPopul__Grenada.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Guadeloupe/run__SynthPopul__Guadeloupe.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Guyana/run__SynthPopul__Guyana.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Paraguay/run__SynthPopul__Paraguay.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Peru/run__SynthPopul__Peru.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/St_Lucia/run__SynthPopul__St_Lucia.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/St_Vincent_The_Grenadines/run__SynthPopul__St_Vincent_The_Grenadines.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Suriname/run__SynthPopul__Suriname.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Trinidad_Tobago/run__SynthPopul__Trinidad_Tobago.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Uruguay/run__SynthPopul__Uruguay.sh
chmod 755 ./bin-linux/SynthPopul/scripts/South_America/Venezuela/run__SynthPopul__Venezuela.sh
