rem This generates the entire synthetic population.
rem Make sure you've checked the REPO definition in run_single.bat first.

call run_single.bat Africa Algeria
call run_single.bat Africa Angola
call run_single.bat Africa Benin
call run_single.bat Africa Botswana
call run_single.bat Africa Burkina_Faso
call run_single.bat Africa Burundi
call run_single.bat Africa Cameroon
call run_single.bat Africa Cape_Verde
call run_single.bat Africa Centr_African_Rep
call run_single.bat Africa Chad
call run_single.bat Africa Comoros
call run_single.bat Africa Congo_Brazzaville
call run_single.bat Africa Congo_Dem_Rep
call run_single.bat Africa Cote_dIvore
call run_single.bat Africa Djibouti
call run_single.bat Africa Egypt
call run_single.bat Africa Equatorial_Guinea
call run_single.bat Africa Eritrea
call run_single.bat Africa Ethiopia
call run_single.bat Africa Gabon
call run_single.bat Africa Gambia
call run_single.bat Africa Ghana
call run_single.bat Africa Guinea
call run_single.bat Africa Guinea-Bissau
call run_single.bat Africa Kenya
call run_single.bat Africa Lesotho
call run_single.bat Africa Liberia
call run_single.bat Africa Libya
call run_single.bat Africa Madagascar
call run_single.bat Africa Malawi
call run_single.bat Africa Mali
call run_single.bat Africa Mauritania
call run_single.bat Africa Mauritius
call run_single.bat Africa Morocco
call run_single.bat Africa Mozambique
call run_single.bat Africa Namibia
call run_single.bat Africa Niger
call run_single.bat Africa Nigeria
call run_single.bat Africa Reunion
call run_single.bat Africa Rwanda
call run_single.bat Africa Sao_Tome_Principe
call run_single.bat Africa Senegal
call run_single.bat Africa Seychelles
call run_single.bat Africa Sierra_Leone
call run_single.bat Africa Somalia
call run_single.bat Africa South_Africa
call run_single.bat Africa Sudan
call run_single.bat Africa Swaziland
call run_single.bat Africa Tanzania
call run_single.bat Africa Togo
call run_single.bat Africa Tunisia
call run_single.bat Africa Uganda
call run_single.bat Africa Zambia
call run_single.bat Africa Zimbabwe
call run_single.bat Asia Afghanistan
call run_single.bat Asia Bahrain
call run_single.bat Asia Bangladesh
call run_single.bat Asia Bhutan
call run_single.bat Asia Burma
call run_single.bat Asia Cambodia
call run_single.bat Asia China
call run_single.bat Asia Hong_Kong
call run_single.bat Asia India
call run_single.bat Asia Indonesia
call run_single.bat Asia Iran
call run_single.bat Asia Iraq
call run_single.bat Asia Israel
call run_single.bat Asia Japan
call run_single.bat Asia Jordan
call run_single.bat Asia Kazakhstan
call run_single.bat Asia Kuwait
call run_single.bat Asia Kyrgyzstan
call run_single.bat Asia Laos
call run_single.bat Asia Lebanon
call run_single.bat Asia Macao
call run_single.bat Asia Malaysia
call run_single.bat Asia Maldives
call run_single.bat Asia Mongolia
call run_single.bat Asia Nepal
call run_single.bat Asia New_Guinea
call run_single.bat Asia NKorea
call run_single.bat Asia Oman
call run_single.bat Asia Pakistan
call run_single.bat Asia Palest_Territory
call run_single.bat Asia Philippines
call run_single.bat Asia Saudi_Arabia
call run_single.bat Asia Singapore
call run_single.bat Asia SKorea
call run_single.bat Asia Sri_Lanka
call run_single.bat Asia Syria
call run_single.bat Asia Taiwan
call run_single.bat Asia Tajikistan
call run_single.bat Asia Thailand
call run_single.bat Asia Timor_Leste
call run_single.bat Asia Turkmenistan
call run_single.bat Asia United_Arab_Emirates
call run_single.bat Asia Uzbekistan
call run_single.bat Asia Vietnam
call run_single.bat Asia Yemen
call run_single.bat Central_America Anguilla
call run_single.bat Central_America Antigua_Barbuda
call run_single.bat Central_America Belize
call run_single.bat Central_America Bermuda
call run_single.bat Central_America Cayman_Islands
call run_single.bat Central_America Costa_Rica
call run_single.bat Central_America Cuba
call run_single.bat Central_America Dominica
call run_single.bat Central_America Dominican_Republic
call run_single.bat Central_America El_Salvador
call run_single.bat Central_America Guatemala
call run_single.bat Central_America Haiti
call run_single.bat Central_America Honduras
call run_single.bat Central_America Jamaica
call run_single.bat Central_America Martinique
call run_single.bat Central_America Montserrat
call run_single.bat Central_America Netherlands_Antilles
call run_single.bat Central_America Nicaragua
call run_single.bat Central_America Panama
call run_single.bat Central_America Puerto_Rico
call run_single.bat Central_America St_Kitts__Nevis
call run_single.bat Central_America The_Bahamas
call run_single.bat Central_America Turks_Caicos_Islands
call run_single.bat Central_America Virgin_Islands_UK
call run_single.bat Central_America Virgin_Islands_US
call run_single.bat Europe Albania
call run_single.bat Europe Andorra
call run_single.bat Europe Armenia
call run_single.bat Europe Austria
call run_single.bat Europe Azerbaijan
call run_single.bat Europe Belarus
call run_single.bat Europe Belgium
call run_single.bat Europe Bosnia_Gerzegovina
call run_single.bat Europe Bulgaria
call run_single.bat Europe Croatia
call run_single.bat Europe Cyprus
call run_single.bat Europe Czech_Republic
call run_single.bat Europe Denmark
call run_single.bat Europe Estonia
call run_single.bat Europe Faroe_Islands
call run_single.bat Europe Finland
call run_single.bat Europe France
call run_single.bat Europe Georgia
call run_single.bat Europe Germany
call run_single.bat Europe Gibraltar
call run_single.bat Europe Greece
call run_single.bat Europe Greenland
call run_single.bat Europe Guernsey
call run_single.bat Europe Hungary
call run_single.bat Europe Iceland
call run_single.bat Europe Ireland
call run_single.bat Europe Isle_of_Man
call run_single.bat Europe Italy
call run_single.bat Europe Jersey
call run_single.bat Europe Latvia
call run_single.bat Europe Liechtenstein
call run_single.bat Europe Lithuania
call run_single.bat Europe Luxembourg
call run_single.bat Europe Macedonia
call run_single.bat Europe Malta
call run_single.bat Europe Moldova
call run_single.bat Europe Monaco
call run_single.bat Europe Netherlands
call run_single.bat Europe Norway
call run_single.bat Europe Poland
call run_single.bat Europe Portugal
call run_single.bat Europe Romania
call run_single.bat Europe Russia
call run_single.bat Europe San_Marino
call run_single.bat Europe Serbia
call run_single.bat Europe Slovakia
call run_single.bat Europe Slovenia
call run_single.bat Europe Spain
call run_single.bat Europe Sweden
call run_single.bat Europe Switzerland
call run_single.bat Europe Turkey
call run_single.bat Europe Ukraine
call run_single.bat Europe United_Kingdom
call run_single.bat North_America Canada
call run_single.bat North_America Mexico
call run_single.bat North_America USA
call run_single.bat Oceania American_Samoa
call run_single.bat Oceania Australia
call run_single.bat Oceania Fiji
call run_single.bat Oceania French_Polynesia
call run_single.bat Oceania Guam
call run_single.bat Oceania Kiribati
call run_single.bat Oceania Marshall_Islands
call run_single.bat Oceania Micronesia
call run_single.bat Oceania New_Caledonia
call run_single.bat Oceania New_Zealand
call run_single.bat Oceania Northern_Mariana_Islands
call run_single.bat Oceania Palau
call run_single.bat Oceania Samoa
call run_single.bat Oceania Solomon_Islands
call run_single.bat Oceania Tonga
call run_single.bat Oceania Tuvalu
call run_single.bat Oceania Vanuatu
call run_single.bat South_America Argentina
call run_single.bat South_America Aruba
call run_single.bat South_America Barbados
call run_single.bat South_America Bolivia
call run_single.bat South_America Brazil
call run_single.bat South_America Chile
call run_single.bat South_America Colombia
call run_single.bat South_America Ecuador
call run_single.bat South_America French_Guiana
call run_single.bat South_America Grenada
call run_single.bat South_America Guadeloupe
call run_single.bat South_America Guyana
call run_single.bat South_America Paraguay
call run_single.bat South_America Peru
call run_single.bat South_America St_Lucia
call run_single.bat South_America St_Vincent_The_Grenadines
call run_single.bat South_America Suriname
call run_single.bat South_America Trinidad_Tobago
call run_single.bat South_America Uruguay
call run_single.bat South_America Venezuela
