#!/bin/bash

% This generates the entire synthetic population.
% Make sure you've checked the REPO definition in run_single.sh first.

./run_single.sh Africa Algeria
./run_single.sh Africa Angola
./run_single.sh Africa Benin
./run_single.sh Africa Botswana
./run_single.sh Africa Burkina_Faso
./run_single.sh Africa Burundi
./run_single.sh Africa Cameroon
./run_single.sh Africa Cape_Verde
./run_single.sh Africa Centr_African_Rep
./run_single.sh Africa Chad
./run_single.sh Africa Comoros
./run_single.sh Africa Congo_Brazzaville
./run_single.sh Africa Congo_Dem_Rep
./run_single.sh Africa Cote_dIvore
./run_single.sh Africa Djibouti
./run_single.sh Africa Egypt
./run_single.sh Africa Equatorial_Guinea
./run_single.sh Africa Eritrea
./run_single.sh Africa Ethiopia
./run_single.sh Africa Gabon
./run_single.sh Africa Gambia
./run_single.sh Africa Ghana
./run_single.sh Africa Guinea
./run_single.sh Africa Guinea-Bissau
./run_single.sh Africa Kenya
./run_single.sh Africa Lesotho
./run_single.sh Africa Liberia
./run_single.sh Africa Libya
./run_single.sh Africa Madagascar
./run_single.sh Africa Malawi
./run_single.sh Africa Mali
./run_single.sh Africa Mauritania
./run_single.sh Africa Mauritius
./run_single.sh Africa Morocco
./run_single.sh Africa Mozambique
./run_single.sh Africa Namibia
./run_single.sh Africa Niger
./run_single.sh Africa Nigeria
./run_single.sh Africa Reunion
./run_single.sh Africa Rwanda
./run_single.sh Africa Sao_Tome_Principe
./run_single.sh Africa Senegal
./run_single.sh Africa Seychelles
./run_single.sh Africa Sierra_Leone
./run_single.sh Africa Somalia
./run_single.sh Africa South_Africa
./run_single.sh Africa Sudan
./run_single.sh Africa Swaziland
./run_single.sh Africa Tanzania
./run_single.sh Africa Togo
./run_single.sh Africa Tunisia
./run_single.sh Africa Uganda
./run_single.sh Africa Zambia
./run_single.sh Africa Zimbabwe
./run_single.sh Asia Afghanistan
./run_single.sh Asia Bahrain
./run_single.sh Asia Bangladesh
./run_single.sh Asia Bhutan
./run_single.sh Asia Burma
./run_single.sh Asia Cambodia
./run_single.sh Asia China
./run_single.sh Asia Hong_Kong
./run_single.sh Asia India
./run_single.sh Asia Indonesia
./run_single.sh Asia Iran
./run_single.sh Asia Iraq
./run_single.sh Asia Israel
./run_single.sh Asia Japan
./run_single.sh Asia Jordan
./run_single.sh Asia Kazakhstan
./run_single.sh Asia Kuwait
./run_single.sh Asia Kyrgyzstan
./run_single.sh Asia Laos
./run_single.sh Asia Lebanon
./run_single.sh Asia Macao
./run_single.sh Asia Malaysia
./run_single.sh Asia Maldives
./run_single.sh Asia Mongolia
./run_single.sh Asia Nepal
./run_single.sh Asia New_Guinea
./run_single.sh Asia NKorea
./run_single.sh Asia Oman
./run_single.sh Asia Pakistan
./run_single.sh Asia Palest_Territory
./run_single.sh Asia Philippines
./run_single.sh Asia Saudi_Arabia
./run_single.sh Asia Singapore
./run_single.sh Asia SKorea
./run_single.sh Asia Sri_Lanka
./run_single.sh Asia Syria
./run_single.sh Asia Taiwan
./run_single.sh Asia Tajikistan
./run_single.sh Asia Thailand
./run_single.sh Asia Timor_Leste
./run_single.sh Asia Turkmenistan
./run_single.sh Asia United_Arab_Emirates
./run_single.sh Asia Uzbekistan
./run_single.sh Asia Vietnam
./run_single.sh Asia Yemen
./run_single.sh Central_America Anguilla
./run_single.sh Central_America Antigua_Barbuda
./run_single.sh Central_America Belize
./run_single.sh Central_America Bermuda
./run_single.sh Central_America Cayman_Islands
./run_single.sh Central_America Costa_Rica
./run_single.sh Central_America Cuba
./run_single.sh Central_America Dominica
./run_single.sh Central_America Dominican_Republic
./run_single.sh Central_America El_Salvador
./run_single.sh Central_America Guatemala
./run_single.sh Central_America Haiti
./run_single.sh Central_America Honduras
./run_single.sh Central_America Jamaica
./run_single.sh Central_America Martinique
./run_single.sh Central_America Montserrat
./run_single.sh Central_America Netherlands_Antilles
./run_single.sh Central_America Nicaragua
./run_single.sh Central_America Panama
./run_single.sh Central_America Puerto_Rico
./run_single.sh Central_America St_Kitts__Nevis
./run_single.sh Central_America The_Bahamas
./run_single.sh Central_America Turks_Caicos_Islands
./run_single.sh Central_America Virgin_Islands_UK
./run_single.sh Central_America Virgin_Islands_US
./run_single.sh Europe Albania
./run_single.sh Europe Andorra
./run_single.sh Europe Armenia
./run_single.sh Europe Austria
./run_single.sh Europe Azerbaijan
./run_single.sh Europe Belarus
./run_single.sh Europe Belgium
./run_single.sh Europe Bosnia_Gerzegovina
./run_single.sh Europe Bulgaria
./run_single.sh Europe Croatia
./run_single.sh Europe Cyprus
./run_single.sh Europe Czech_Republic
./run_single.sh Europe Denmark
./run_single.sh Europe Estonia
./run_single.sh Europe Faroe_Islands
./run_single.sh Europe Finland
./run_single.sh Europe France
./run_single.sh Europe Georgia
./run_single.sh Europe Germany
./run_single.sh Europe Gibraltar
./run_single.sh Europe Greece
./run_single.sh Europe Greenland
./run_single.sh Europe Guernsey
./run_single.sh Europe Hungary
./run_single.sh Europe Iceland
./run_single.sh Europe Ireland
./run_single.sh Europe Isle_of_Man
./run_single.sh Europe Italy
./run_single.sh Europe Jersey
./run_single.sh Europe Latvia
./run_single.sh Europe Liechtenstein
./run_single.sh Europe Lithuania
./run_single.sh Europe Luxembourg
./run_single.sh Europe Macedonia
./run_single.sh Europe Malta
./run_single.sh Europe Moldova
./run_single.sh Europe Monaco
./run_single.sh Europe Netherlands
./run_single.sh Europe Norway
./run_single.sh Europe Poland
./run_single.sh Europe Portugal
./run_single.sh Europe Romania
./run_single.sh Europe Russia
./run_single.sh Europe San_Marino
./run_single.sh Europe Serbia
./run_single.sh Europe Slovakia
./run_single.sh Europe Slovenia
./run_single.sh Europe Spain
./run_single.sh Europe Sweden
./run_single.sh Europe Switzerland
./run_single.sh Europe Turkey
./run_single.sh Europe Ukraine
./run_single.sh Europe United_Kingdom
./run_single.sh North_America Canada
./run_single.sh North_America Mexico
./run_single.sh North_America USA
./run_single.sh Oceania American_Samoa
./run_single.sh Oceania Australia
./run_single.sh Oceania Fiji
./run_single.sh Oceania French_Polynesia
./run_single.sh Oceania Guam
./run_single.sh Oceania Kiribati
./run_single.sh Oceania Marshall_Islands
./run_single.sh Oceania Micronesia
./run_single.sh Oceania New_Caledonia
./run_single.sh Oceania New_Zealand
./run_single.sh Oceania Northern_Mariana_Islands
./run_single.sh Oceania Palau
./run_single.sh Oceania Samoa
./run_single.sh Oceania Solomon_Islands
./run_single.sh Oceania Tonga
./run_single.sh Oceania Tuvalu
./run_single.sh Oceania Vanuatu
./run_single.sh South_America Argentina
./run_single.sh South_America Aruba
./run_single.sh South_America Barbados
./run_single.sh South_America Bolivia
./run_single.sh South_America Brazil
./run_single.sh South_America Chile
./run_single.sh South_America Colombia
./run_single.sh South_America Ecuador
./run_single.sh South_America French_Guiana
./run_single.sh South_America Grenada
./run_single.sh South_America Guadeloupe
./run_single.sh South_America Guyana
./run_single.sh South_America Paraguay
./run_single.sh South_America Peru
./run_single.sh South_America St_Lucia
./run_single.sh South_America St_Vincent_The_Grenadines
./run_single.sh South_America Suriname
./run_single.sh South_America Trinidad_Tobago
./run_single.sh South_America Uruguay
./run_single.sh South_America Venezuela
